version: '2.1'
services:
  mongo-db:
    image: mongo:latest
    ports:
      - 27017:27017
  gc-test-node:
    build: ./nodejs
    depends_on:
      - mongo-db
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 0.5
  gc-test-go:
    build: ./go
    depends_on:
      - mongo-db
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 0.5
